version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: studymate
      POSTGRES_USER: studymate
      POSTGRES_PASSWORD: studymate
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studymate"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    environment:
      MINIO_ROOT_USER: studymate
      MINIO_ROOT_PASSWORD: studymate
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env.example
    environment:
      APP_ENV: dev
      POSTGRES_URL: postgresql+psycopg://studymate:studymate@db:5432/studymate
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: studymate
      S3_ACCESS_KEY: studymate
      S3_SECRET_KEY: studymate
      EMBEDDINGS_BACKEND: sentence-transformers
      EMBEDDINGS_MODEL: BAAI/bge-small-en-v1.5
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - faiss_data:/data/faiss
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --port 3000

volumes:
  db_data:
  minio_data:
  faiss_data:


